export const LOGINED =  "LOGINED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const FB_SIGNUP_SUCCESS = "FB_SIGNUP_SUCCESS";
export const GG_SIGNUP_SUCCESS = "GG_SIGNUP_SUCCESS";
export const FB_LOGIN_SUCCESS = "FB_LOGIN_SUCCESS";
export const GG_LOGIN_SUCCESS = "GG_LOGIN_SUCCESS";
export const SYNC_AUTH_STATUS = "SYNC_AUTH_STATUS";

export const QUERY_LOCAL_SONG  = "QUERY_LOCAL_SONG";
export const MINI_PLAYER_STATE = "MINI_PLAYER_STATE";

export const SYNC_NAVIGATION_PROPS= "SYNC_NAVIGATION_PROPS";

export const SYNC_CURRENT_TRACK = "SYNC_CURRENT_TRACK";
